// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwRaVbP50pOATcKGUqyG1q3yo0XDnR950',
    appId: '1:343066555968:web:4c27ab82925022d5c0d1a5',
    messagingSenderId: '343066555968',
    projectId: 'forkcast-c8d06',
    authDomain: 'forkcast-c8d06.firebaseapp.com',
    storageBucket: 'forkcast-c8d06.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD31nQkgsPXhyb1gHuRtbVZ4bC3toG0HIY',
    appId: '1:343066555968:android:5b28a74d000cfdb3c0d1a5',
    messagingSenderId: '343066555968',
    projectId: 'forkcast-c8d06',
    storageBucket: 'forkcast-c8d06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV8eyPhBmOu55XinMJ1ozpU14Vsj2jv6I',
    appId: '1:343066555968:ios:420bcc2823e7ea16c0d1a5',
    messagingSenderId: '343066555968',
    projectId: 'forkcast-c8d06',
    storageBucket: 'forkcast-c8d06.firebasestorage.app',
    iosBundleId: 'com.example.lab07Example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV8eyPhBmOu55XinMJ1ozpU14Vsj2jv6I',
    appId: '1:343066555968:ios:420bcc2823e7ea16c0d1a5',
    messagingSenderId: '343066555968',
    projectId: 'forkcast-c8d06',
    storageBucket: 'forkcast-c8d06.firebasestorage.app',
    iosBundleId: 'com.example.lab07Example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwRaVbP50pOATcKGUqyG1q3yo0XDnR950',
    appId: '1:343066555968:web:c1ff5f4a6ef2693ac0d1a5',
    messagingSenderId: '343066555968',
    projectId: 'forkcast-c8d06',
    authDomain: 'forkcast-c8d06.firebaseapp.com',
    storageBucket: 'forkcast-c8d06.firebasestorage.app',
  );
}
