// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWLQvbNzLWjNxHVpV8AchD_4geD26YU6Y',
    appId: '1:268007894301:web:989afe4c04e80b012745f4',
    messagingSenderId: '268007894301',
    projectId: 'forkcast-test-version',
    authDomain: 'forkcast-test-version.firebaseapp.com',
    storageBucket: 'forkcast-test-version.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEMar2c_UqhkLHIjQ6wh9M5ywNp3wgOL4',
    appId: '1:268007894301:android:2f4ed77895bf4f3e2745f4',
    messagingSenderId: '268007894301',
    projectId: 'forkcast-test-version',
    storageBucket: 'forkcast-test-version.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7L2Wd1riTooZtXW4ykHxDvbgy8Wajt84',
    appId: '1:268007894301:ios:d7f21bbf6e81bdb32745f4',
    messagingSenderId: '268007894301',
    projectId: 'forkcast-test-version',
    storageBucket: 'forkcast-test-version.firebasestorage.app',
    iosBundleId: 'com.example.lab07Example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7L2Wd1riTooZtXW4ykHxDvbgy8Wajt84',
    appId: '1:268007894301:ios:d7f21bbf6e81bdb32745f4',
    messagingSenderId: '268007894301',
    projectId: 'forkcast-test-version',
    storageBucket: 'forkcast-test-version.firebasestorage.app',
    iosBundleId: 'com.example.lab07Example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWLQvbNzLWjNxHVpV8AchD_4geD26YU6Y',
    appId: '1:268007894301:web:6a99d762cd10e21b2745f4',
    messagingSenderId: '268007894301',
    projectId: 'forkcast-test-version',
    authDomain: 'forkcast-test-version.firebaseapp.com',
    storageBucket: 'forkcast-test-version.firebasestorage.app',
  );

}